apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: master
  name: database
spec:
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init
          image: spicaengine/initcontainer:master
          imagePullPolicy: Always
      containers:
        - name: mongo
          image: mongo:4.2
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "250Mi"
              cpu: "150m"
          volumeMounts:
            - name: master-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: master-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: master
  name: mongo
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: database
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: master
  name: spica
spec:
  serviceName: spica
  replicas: 1
  template:
    metadata:
      labels:
        app: spica
    spec:
      containers:
        - name: spica
          image: spicaengine/spica:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "50m"
        - name: api
          image: spicaengine/api:master
          imagePullPolicy: Always
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "250Mi"
              cpu: "150m"
          ports:
            - containerPort: 4300
          env:
            - name: PORT
              value: "4300"
            - name: DATABASE_URI
              value: mongodb://database-0.mongo.master.svc.cluster.local,database-1.mongo.master.svc.cluster.local,database-2.mongo.master.svc.cluster.local
            - name: REPLICA_SET
              value: rs0
            - name: DATABASE_NAME
              value: spica
            - name: SECRET
              value: $2b$10$shOzfYpDCy.RMgsVlwdQeONKGGzaBTfTQAjmXQNpMp4aKlLXrfZ/C
            - name: DEFAULT_PASSWORD
              value: spica
            - name: PUBLIC_HOST
              value: "https://master.spicaengine.com/api"
            - name: PERSISTENT_PATH
              value: /data
          volumeMounts:
            - name: master-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: master-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: master
  name: spica
spec:
  type: NodePort
  ports:
    - name: spica
      port: 80
      targetPort: 80
    - name: api
      port: 4300
      targetPort: 4300
  selector:
    app: spica
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: master
  name: gateway
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 15M
    nginx.ingress.kubernetes.io/client-body-buffer-size: 15M
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - master.spicaengine.com
      secretName: master-spica
  rules:
    - host: master.spicaengine.com
      http:
        paths:
          - path: /spica/?(.*)
            backend:
              serviceName: spica
              servicePort: 80
          - path: /api/?(.*)
            backend:
              serviceName: spica
              servicePort: 4300
