apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init
          image: gcr.io/spica-239113/initcontainer
          imagePullPolicy: Always
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: database-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: database-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: true
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: database
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: spica
spec:
  serviceName: spica
  replicas: 1
  template:
    metadata:
      labels:
        app: spica
    spec:
      containers:
        - name: spica
          image: gcr.io/spica-239113/spica
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: api
          image: gcr.io/spica-239113/api
          imagePullPolicy: Always
          ports:
            - containerPort: 4300
          env:
            - name: PORT
              value: "4300"
            - name: DATABASE_URI
              value: mongodb://database-0.mongo.default.svc.cluster.local,database-1.mongo.default.svc.cluster.local,database-2.mongo.default.svc.cluster.local
            - name: REPLICA_SET
              value: rs0
            - name: DATABASE_NAME
              value: spica
            - name: PUBLIC_HOST
              # TODO(thesayyn): https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
              value: 'https://35.239.247.158/api'
            - name: PERSISTENT_PATH
              value: /data
          volumeMounts:
            - name: spica-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: spica-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: spica
spec:
  type: NodePort
  ports:
    - name: spica
      port: 80
      targetPort: 80
    - name: api
      port: 4300
      targetPort: 4300
  selector:
    app: spica
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /spica/?(.*)
            backend:
              serviceName: spica
              servicePort: 80
          - path: /api/?(.*)
            backend:
              serviceName: spica
              servicePort: 4300
