apiVersion: bucket/v1
kind: Schema
metadata:
  name: roles
spec:
  title: Roles
  description: User roles
  icon: outbond
  required:
    - name
  properties:
    name:
      type: string
    created_at:
      type: date
      default: :created_at
    updated_at:
      type: date
      default: :updated_at
---
apiVersion: bucket/v1
kind: Schema
metadata:
  name: user
spec:
  title: Userss
  description: Users
  icon: perm_identity
  required:
    - email
  properties:
    email:
      type: string
    role:
      type: relation
      bucket:
        valueFrom:
          resourceFieldRef:
            bucketName: roles
    created_at:
      type: date
      default: :created_at
    updated_at:
      type: date
      default: :updated_at
    activated_at:
      type: date
---
apiVersion: function/v1
kind: Function
metadata:
  name: test
spec:
  title: Email
  description: Users
  language: Javascript
  code: ./test.js
  trigger:
    default:
      type: http
      active: True
      options:
        method: Get
        path: "/test"

  environment:
    - key: TEST
      value: "LITERAL"

    - key: BUCKET_ID
      valueFrom:
        resourceFieldRef:
          bucketName: roles
