apiVersion: bucket/v1
kind: Schema
metadata:
  name: roles
spec:
  title: Roles 🥴🤘
  description: User roles
  icon: outbond
  required:
    - name
  properties:
    name:
      type: string
    created_at:
      type: date
      default: :created_at
    updated_at:
      type: datee
      default: :updated_at
