
kind: Bucket
apiVersion: v1
metadata:
  name: email
spec:
  title: Emails
  description: Email Queue
  required:
    - email
  properties:
    email:
      type: string
    created_at:
      type: date
      default: :created_at
    updated_at:
      type: date
      default: :updated_at
    delivered_at:
      type: date
# ---
# kind: Bucket
# apiVersion: v1
# metadata:
#   name: email
# spec:
#   title: Emails
#   description: Email Queue
#   required:
#     - email
#   properties:
#     email:
#       type: string
#     created_at:
#       type: date
#       default: :created_at
#     updated_at:
#       type: date
#       default: :updated_at
#     delivered_at:
#       type: date