import {Component} from "@angular/core";
import {Router} from "@angular/router";
import {PreferencesService} from "@spica-client/core";

import {BucketSettings} from "../../interfaces/bucket-settings";

@Component({
  selector: "bucket-settings",
  templateUrl: "./settings.component.html",
  styleUrls: ["./settings.component.scss"]
})
export class SettingsComponent {
  public bucketSettings: BucketSettings;
  public langs = [
    {short: "af", long: "Afrikaans"},
    {short: "af-ZA", long: "Afrikaans (South Africa)"},
    {short: "ar", long: "Arabic"},
    {short: "ar-AE", long: "Arabic (U.A.E.)"},
    {short: "ar-BH", long: "Arabic (Bahrain)"},
    {short: "ar-DZ", long: "Arabic (Algeria)"},
    {short: "ar-EG", long: "Arabic (Egypt)"},
    {short: "ar-IQ", long: "Arabic (Iraq)"},
    {short: "ar-JO", long: "Arabic (Jordan)"},
    {short: "ar-KW", long: "Arabic (Kuwait)"},
    {short: "ar-LB", long: "Arabic (Lebanon)"},
    {short: "ar-LY", long: "Arabic (Libya)"},
    {short: "ar-MA", long: "Arabic (Morocco)"},
    {short: "ar-OM", long: "Arabic (Oman)"},
    {short: "ar-QA", long: "Arabic (Qatar)"},
    {short: "ar-SA", long: "Arabic (Saudi Arabia)"},
    {short: "ar-SY", long: "Arabic (Syria)"},
    {short: "ar-TN", long: "Arabic (Tunisia)"},
    {short: "ar-YE", long: "Arabic (Yemen)"},
    {short: "az", long: "Azeri (Latin)"},
    {short: "az-AZ", long: "Azeri (Latin) (Azerbaijan)"},
    {short: "az-AZ", long: "Azeri (Cyrillic) (Azerbaijan)"},
    {short: "be", long: "Belarusian"},
    {short: "be-BY", long: "Belarusian (Belarus)"},
    {short: "bg", long: "Bulgarian"},
    {short: "bg-BG", long: "Bulgarian (Bulgaria)"},
    {short: "bs-BA", long: "Bosnian (Bosnia and Herzegovina)"},
    {short: "ca", long: "Catalan"},
    {short: "ca-ES", long: "Catalan (Spain)"},
    {short: "cs", long: "Czech"},
    {short: "cs-CZ", long: "Czech (Czech Republic)"},
    {short: "cy", long: "Welsh"},
    {short: "cy-GB", long: "Welsh (United Kingdom)"},
    {short: "da", long: "Danish"},
    {short: "da-DK", long: "Danish (Denmark)"},
    {short: "de", long: "German"},
    {short: "de-AT", long: "German (Austria)"},
    {short: "de-CH", long: "German (Switzerland)"},
    {short: "de-DE", long: "German (Germany)"},
    {short: "de-LI", long: "German (Liechtenstein)"},
    {short: "de-LU", long: "German (Luxembourg)"},
    {short: "dv", long: "Divehi"},
    {short: "dv-MV", long: "Divehi (Maldives)"},
    {short: "el", long: "Greek"},
    {short: "el-GR", long: "Greek (Greece)"},
    {short: "en", long: "English"},
    {short: "en-AU", long: "English (Australia)"},
    {short: "en-BZ", long: "English (Belize)"},
    {short: "en-CA", long: "English (Canada)"},
    {short: "en-CB", long: "English (Caribbean)"},
    {short: "en-GB", long: "English (United Kingdom)"},
    {short: "en-IE", long: "English (Ireland)"},
    {short: "en-JM", long: "English (Jamaica)"},
    {short: "en-NZ", long: "English (New Zealand)"},
    {short: "en-PH", long: "English (Republic of the Philippines)"},
    {short: "en-TT", long: "English (Trinidad and Tobago)"},
    {short: "en-US", long: "English (United States)"},
    {short: "en-ZA", long: "English (South Africa)"},
    {short: "en-ZW", long: "English (Zimbabwe)"},
    {short: "eo", long: "Esperanto"},
    {short: "es", long: "Spanish"},
    {short: "es-AR", long: "Spanish (Argentina)"},
    {short: "es-BO", long: "Spanish (Bolivia)"},
    {short: "es-CL", long: "Spanish (Chile)"},
    {short: "es-CO", long: "Spanish (Colombia)"},
    {short: "es-CR", long: "Spanish (Costa Rica)"},
    {short: "es-DO", long: "Spanish (Dominican Republic)"},
    {short: "es-EC", long: "Spanish (Ecuador)"},
    {short: "es-ES", long: "Spanish (Castilian)"},
    {short: "es-ES", long: "Spanish (Spain)"},
    {short: "es-GT", long: "Spanish (Guatemala)"},
    {short: "es-HN", long: "Spanish (Honduras)"},
    {short: "es-MX", long: "Spanish (Mexico)"},
    {short: "es-NI", long: "Spanish (Nicaragua)"},
    {short: "es-PA", long: "Spanish (Panama)"},
    {short: "es-PE", long: "Spanish (Peru)"},
    {short: "es-PR", long: "Spanish (Puerto Rico)"},
    {short: "es-PY", long: "Spanish (Paraguay)"},
    {short: "es-SV", long: "Spanish (El Salvador)"},
    {short: "es-UY", long: "Spanish (Uruguay)"},
    {short: "es-VE", long: "Spanish (Venezuela)"},
    {short: "et", long: "Estonian"},
    {short: "et-EE", long: "Estonian (Estonia)"},
    {short: "eu", long: "Basque"},
    {short: "eu-ES", long: "Basque (Spain)"},
    {short: "fa", long: "Farsi"},
    {short: "fa-IR", long: "Farsi (Iran)"},
    {short: "fi", long: "Finnish"},
    {short: "fi-FI", long: "Finnish (Finland)"},
    {short: "fo", long: "Faroese"},
    {short: "fo-FO", long: "Faroese (Faroe Islands)"},
    {short: "fr", long: "French"},
    {short: "fr-BE", long: "French (Belgium)"},
    {short: "fr-CA", long: "French (Canada)"},
    {short: "fr-CH", long: "French (Switzerland)"},
    {short: "fr-FR", long: "French (France)"},
    {short: "fr-LU", long: "French (Luxembourg)"},
    {short: "fr-MC", long: "French (Principality of Monaco)"},
    {short: "gl", long: "Galician"},
    {short: "gl-ES", long: "Galician (Spain)"},
    {short: "gu", long: "Gujarati"},
    {short: "gu-IN", long: "Gujarati (India)"},
    {short: "he", long: "Hebrew"},
    {short: "he-IL", long: "Hebrew (Israel)"},
    {short: "hi", long: "Hindi"},
    {short: "hi-IN", long: "Hindi (India)"},
    {short: "hr", long: "Croatian"},
    {short: "hr-BA", long: "Croatian (Bosnia and Herzegovina)"},
    {short: "hr-HR", long: "Croatian (Croatia)"},
    {short: "hu", long: "Hungarian"},
    {short: "hu-HU", long: "Hungarian (Hungary)"},
    {short: "hy", long: "Armenian"},
    {short: "hy-AM", long: "Armenian (Armenia)"},
    {short: "id", long: "Indonesian"},
    {short: "id-ID", long: "Indonesian (Indonesia)"},
    {short: "is", long: "Icelandic"},
    {short: "is-IS", long: "Icelandic (Iceland)"},
    {short: "it", long: "Italian"},
    {short: "it-CH", long: "Italian (Switzerland)"},
    {short: "it-IT", long: "Italian (Italy)"},
    {short: "ja", long: "Japanese"},
    {short: "ja-JP", long: "Japanese (Japan)"},
    {short: "ka", long: "Georgian"},
    {short: "ka-GE", long: "Georgian (Georgia)"},
    {short: "kk", long: "Kazakh"},
    {short: "kk-KZ", long: "Kazakh (Kazakhstan)"},
    {short: "kn", long: "Kannada"},
    {short: "kn-IN", long: "Kannada (India)"},
    {short: "ko", long: "Korean"},
    {short: "ko-KR", long: "Korean (Korea)"},
    {short: "kok", long: "Konkani"},
    {short: "kok-IN", long: "Konkani (India)"},
    {short: "ky", long: "Kyrgyz"},
    {short: "ky-KG", long: "Kyrgyz (Kyrgyzstan)"},
    {short: "lt", long: "Lithuanian"},
    {short: "lt-LT", long: "Lithuanian (Lithuania)"},
    {short: "lv", long: "Latvian"},
    {short: "lv-LV", long: "Latvian (Latvia)"},
    {short: "mi", long: "Maori"},
    {short: "mi-NZ", long: "Maori (New Zealand)"},
    {short: "mk", long: "FYRO Macedonian"},
    {short: "mk-MK", long: "FYRO Macedonian (Former Yugoslav Republic of Macedonia)"},
    {short: "mn", long: "Mongolian"},
    {short: "mn-MN", long: "Mongolian (Mongolia)"},
    {short: "mr", long: "Marathi"},
    {short: "mr-IN", long: "Marathi (India)"},
    {short: "ms", long: "Malay"},
    {short: "ms-BN", long: "Malay (Brunei Darussalam)"},
    {short: "ms-MY", long: "Malay (Malaysia)"},
    {short: "mt", long: "Maltese"},
    {short: "mt-MT", long: "Maltese (Malta)"},
    {short: "nb", long: "Norwegian (Bokm?l)"},
    {short: "nb-NO", long: "Norwegian (Bokm?l) (Norway)"},
    {short: "nl", long: "Dutch"},
    {short: "nl-BE", long: "Dutch (Belgium)"},
    {short: "nl-NL", long: "Dutch (Netherlands)"},
    {short: "nn-NO", long: "Norwegian (Nynorsk) (Norway)"},
    {short: "ns", long: "Northern Sotho"},
    {short: "ns-ZA", long: "Northern Sotho (South Africa)"},
    {short: "pa", long: "Punjabi"},
    {short: "pa-IN", long: "Punjabi (India)"},
    {short: "pl", long: "Polish"},
    {short: "pl-PL", long: "Polish (Poland)"},
    {short: "ps", long: "Pashto"},
    {short: "ps-AR", long: "Pashto (Afghanistan)"},
    {short: "pt", long: "Portuguese"},
    {short: "pt-BR", long: "Portuguese (Brazil)"},
    {short: "pt-PT", long: "Portuguese (Portugal)"},
    {short: "qu", long: "Quechua"},
    {short: "qu-BO", long: "Quechua (Bolivia)"},
    {short: "qu-EC", long: "Quechua (Ecuador)"},
    {short: "qu-PE", long: "Quechua (Peru)"},
    {short: "ro", long: "Romanian"},
    {short: "ro-RO", long: "Romanian (Romania)"},
    {short: "ru", long: "Russian"},
    {short: "ru-RU", long: "Russian (Russia)"},
    {short: "sa", long: "Sanskrit"},
    {short: "sa-IN", long: "Sanskrit (India)"},
    {short: "se", long: "Sami (Northern)"},
    {short: "se-FI", long: "Sami (Northern) (Finland)"},
    {short: "se-FI", long: "Sami (Skolt) (Finland)"},
    {short: "se-FI", long: "Sami (Inari) (Finland)"},
    {short: "se-NO", long: "Sami (Northern) (Norway)"},
    {short: "se-NO", long: "Sami (Lule) (Norway)"},
    {short: "se-NO", long: "Sami (Southern) (Norway)"},
    {short: "se-SE", long: "Sami (Northern) (Sweden)"},
    {short: "se-SE", long: "Sami (Lule) (Sweden)"},
    {short: "se-SE", long: "Sami (Southern) (Sweden)"},
    {short: "sk", long: "Slovak"},
    {short: "sk-SK", long: "Slovak (Slovakia)"},
    {short: "sl", long: "Slovenian"},
    {short: "sl-SI", long: "Slovenian (Slovenia)"},
    {short: "sq", long: "Albanian"},
    {short: "sq-AL", long: "Albanian (Albania)"},
    {short: "sr-BA", long: "Serbian (Latin) (Bosnia and Herzegovina)"},
    {short: "sr-BA", long: "Serbian (Cyrillic) (Bosnia and Herzegovina)"},
    {short: "sr-SP", long: "Serbian (Latin) (Serbia and Montenegro)"},
    {short: "sr-SP", long: "Serbian (Cyrillic) (Serbia and Montenegro)"},
    {short: "sv", long: "Swedish"},
    {short: "sv-FI", long: "Swedish (Finland)"},
    {short: "sv-SE", long: "Swedish (Sweden)"},
    {short: "sw", long: "Swahili"},
    {short: "sw-KE", long: "Swahili (Kenya)"},
    {short: "syr", long: "Syriac"},
    {short: "syr-SY", long: "Syriac (Syria)"},
    {short: "ta", long: "Tamil"},
    {short: "ta-IN", long: "Tamil (India)"},
    {short: "te", long: "Telugu"},
    {short: "te-IN", long: "Telugu (India)"},
    {short: "th", long: "Thai"},
    {short: "th-TH", long: "Thai (Thailand)"},
    {short: "tl", long: "Tagalog"},
    {short: "tl-PH", long: "Tagalog (Philippines)"},
    {short: "tn", long: "Tswana"},
    {short: "tn-ZA", long: "Tswana (South Africa)"},
    {short: "tr", long: "Turkish"},
    {short: "tr-TR", long: "Turkish (Turkey)"},
    {short: "tt", long: "Tatar"},
    {short: "tt-RU", long: "Tatar (Russia)"},
    {short: "ts", long: "Tsonga"},
    {short: "uk", long: "Ukrainian"},
    {short: "uk-UA", long: "Ukrainian (Ukraine)"},
    {short: "ur", long: "Urdu"},
    {short: "ur-PK", long: "Urdu (Islamic Republic of Pakistan)"},
    {short: "uz", long: "Uzbek (Latin)"},
    {short: "uz-UZ", long: "Uzbek (Latin) (Uzbekistan)"},
    {short: "uz-UZ", long: "Uzbek (Cyrillic) (Uzbekistan)"},
    {short: "vi", long: "Vietnamese"},
    {short: "vi-VN", long: "Vietnamese (Viet Nam)"},
    {short: "xh", long: "Xhosa"},
    {short: "xh-ZA", long: "Xhosa (South Africa)"},
    {short: "zh", long: "Chinese"},
    {short: "zh-CN", long: "Chinese (S)"},
    {short: "zh-HK", long: "Chinese (Hong Kong)"},
    {short: "zh-MO", long: "Chinese (Macau)"},
    {short: "zh-SG", long: "Chinese (Singapore)"},
    {short: "zh-TW", long: "Chinese (T)"},
    {short: "zu", long: "Zulu"},
    {short: "zu-ZA", long: "Zulu (South Africa) "}
  ];

  constructor(private router: Router, private pref: PreferencesService) {
    pref.get<BucketSettings>("bucket").subscribe(settings => (this.bucketSettings = settings));
  }

  addLanguage(name: string, code: string) {
    const {
      language: {supported_languages}
    } = this.bucketSettings;

    supported_languages.push({name, code});
  }

  updateSettings(): void {
    this.pref.update(this.bucketSettings).subscribe(() => this.router.navigate(["buckets"]));
  }
}
