apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-application
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  rules:
      {{if .Values.ingress.host}}
    - host: {{.Values.ingress.host}}
      http:
      {{else}}
    - http:
      {{end}}
        paths:
          - path: {{.Values.application.webBaseUrl}}?(.*)
            backend:
              serviceName: {{ .Release.Name }}-application
              servicePort: 80
          - path: {{.Values.application.apiBaseUrl}}?(.*)
            backend:
              serviceName: {{ .Release.Name }}-application
              servicePort: 4300