/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.3
 * source: grpc.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace Grpc {
  export class Request extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            id?: string;
            body?: string;
          }
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        if ("body" in data && data.body != undefined) {
          this.body = data.body;
        }
      }
    }
    get id() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get body() {
      return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set body(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    static fromObject(data: {id?: string; body?: string}): Request {
      const message = new Request({});
      if (data.id != null) {
        message.id = data.id;
      }
      if (data.body != null) {
        message.body = data.body;
      }
      return message;
    }
    toObject() {
      const data: {id?: string; body?: string} = {};
      if (this.id != null) {
        data.id = this.id;
      }
      if (this.body != null) {
        data.body = this.body;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id.length) writer.writeString(1, this.id);
      if (this.body.length) writer.writeString(2, this.body);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Request {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new Request();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.id = reader.readString();
            break;
          case 2:
            message.body = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Request {
      return Request.deserialize(bytes);
    }
  }
  export namespace Request {
    export class Pop extends pb_1.Message {
      #one_of_decls: number[][] = [];
      constructor(
        data?:
          | any[]
          | {
              id?: string;
            }
      ) {
        super();
        pb_1.Message.initialize(
          this,
          Array.isArray(data) ? data : [],
          0,
          -1,
          [],
          this.#one_of_decls
        );
        if (!Array.isArray(data) && typeof data == "object") {
          if ("id" in data && data.id != undefined) {
            this.id = data.id;
          }
        }
      }
      get id() {
        return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
      }
      set id(value: string) {
        pb_1.Message.setField(this, 1, value);
      }
      static fromObject(data: {id?: string}): Pop {
        const message = new Pop({});
        if (data.id != null) {
          message.id = data.id;
        }
        return message;
      }
      toObject() {
        const data: {id?: string} = {};
        if (this.id != null) {
          data.id = this.id;
        }
        return data;
      }
      serialize(): Uint8Array;
      serialize(w: pb_1.BinaryWriter): void;
      serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (this.id.length) writer.writeString(1, this.id);
        if (!w) return writer.getResultBuffer();
      }
      static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Pop {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
          message = new Pop();
        while (reader.nextField()) {
          if (reader.isEndGroup()) break;
          switch (reader.getFieldNumber()) {
            case 1:
              message.id = reader.readString();
              break;
            default:
              reader.skipField();
          }
        }
        return message;
      }
      serializeBinary(): Uint8Array {
        return this.serialize();
      }
      static deserializeBinary(bytes: Uint8Array): Pop {
        return Pop.deserialize(bytes);
      }
    }
  }
  export class Response extends pb_1.Message {
    #one_of_decls: number[][] = [];
    constructor(
      data?:
        | any[]
        | {
            id?: string;
            body?: string;
            statusCode?: number;
            error?: string;
          }
    ) {
      super();
      pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
      if (!Array.isArray(data) && typeof data == "object") {
        if ("id" in data && data.id != undefined) {
          this.id = data.id;
        }
        if ("body" in data && data.body != undefined) {
          this.body = data.body;
        }
        if ("statusCode" in data && data.statusCode != undefined) {
          this.statusCode = data.statusCode;
        }
        if ("error" in data && data.error != undefined) {
          this.error = data.error;
        }
      }
    }
    get id() {
      return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
    }
    set id(value: string) {
      pb_1.Message.setField(this, 1, value);
    }
    get body() {
      return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
    }
    set body(value: string) {
      pb_1.Message.setField(this, 2, value);
    }
    get statusCode() {
      return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
    }
    set statusCode(value: number) {
      pb_1.Message.setField(this, 3, value);
    }
    get error() {
      return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
    }
    set error(value: string) {
      pb_1.Message.setField(this, 4, value);
    }
    static fromObject(data: {
      id?: string;
      body?: string;
      statusCode?: number;
      error?: string;
    }): Response {
      const message = new Response({});
      if (data.id != null) {
        message.id = data.id;
      }
      if (data.body != null) {
        message.body = data.body;
      }
      if (data.statusCode != null) {
        message.statusCode = data.statusCode;
      }
      if (data.error != null) {
        message.error = data.error;
      }
      return message;
    }
    toObject() {
      const data: {id?: string; body?: string; statusCode?: number; error?: string} = {};
      if (this.id != null) {
        data.id = this.id;
      }
      if (this.body != null) {
        data.body = this.body;
      }
      if (this.statusCode != null) {
        data.statusCode = this.statusCode;
      }
      if (this.error != null) {
        data.error = this.error;
      }
      return data;
    }
    serialize(): Uint8Array;
    serialize(w: pb_1.BinaryWriter): void;
    serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
      const writer = w || new pb_1.BinaryWriter();
      if (this.id.length) writer.writeString(1, this.id);
      if (this.body.length) writer.writeString(2, this.body);
      if (this.statusCode != 0) writer.writeInt32(3, this.statusCode);
      if (this.error.length) writer.writeString(4, this.error);
      if (!w) return writer.getResultBuffer();
    }
    static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Response {
      const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
        message = new Response();
      while (reader.nextField()) {
        if (reader.isEndGroup()) break;
        switch (reader.getFieldNumber()) {
          case 1:
            message.id = reader.readString();
            break;
          case 2:
            message.body = reader.readString();
            break;
          case 3:
            message.statusCode = reader.readInt32();
            break;
          case 4:
            message.error = reader.readString();
            break;
          default:
            reader.skipField();
        }
      }
      return message;
    }
    serializeBinary(): Uint8Array {
      return this.serialize();
    }
    static deserializeBinary(bytes: Uint8Array): Response {
      return Response.deserialize(bytes);
    }
  }
  export namespace Response {
    export class Result extends pb_1.Message {
      #one_of_decls: number[][] = [];
      constructor(data?: any[] | {}) {
        super();
        pb_1.Message.initialize(
          this,
          Array.isArray(data) ? data : [],
          0,
          -1,
          [],
          this.#one_of_decls
        );
        if (!Array.isArray(data) && typeof data == "object") {
        }
      }
      static fromObject(data: {}): Result {
        const message = new Result({});
        return message;
      }
      toObject() {
        const data: {} = {};
        return data;
      }
      serialize(): Uint8Array;
      serialize(w: pb_1.BinaryWriter): void;
      serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
        const writer = w || new pb_1.BinaryWriter();
        if (!w) return writer.getResultBuffer();
      }
      static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Result {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes),
          message = new Result();
        while (reader.nextField()) {
          if (reader.isEndGroup()) break;
          switch (reader.getFieldNumber()) {
            default:
              reader.skipField();
          }
        }
        return message;
      }
      serializeBinary(): Uint8Array {
        return this.serialize();
      }
      static deserializeBinary(bytes: Uint8Array): Result {
        return Result.deserialize(bytes);
      }
    }
  }
  interface GrpcUnaryServiceInterface<P, R> {
    (
      message: P,
      metadata: grpc_1.Metadata,
      options: grpc_1.CallOptions,
      callback: grpc_1.requestCallback<R>
    ): grpc_1.ClientUnaryCall;
    (
      message: P,
      metadata: grpc_1.Metadata,
      callback: grpc_1.requestCallback<R>
    ): grpc_1.ClientUnaryCall;
    (
      message: P,
      options: grpc_1.CallOptions,
      callback: grpc_1.requestCallback<R>
    ): grpc_1.ClientUnaryCall;
    (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
  }
  export abstract class UnimplementedQueueService {
    static definition = {
      pop: {
        path: "/Grpc.Queue/pop",
        requestStream: false,
        responseStream: false,
        requestSerialize: (message: Request.Pop) => Buffer.from(message.serialize()),
        requestDeserialize: (bytes: Buffer) => Request.Pop.deserialize(new Uint8Array(bytes)),
        responseSerialize: (message: Request) => Buffer.from(message.serialize()),
        responseDeserialize: (bytes: Buffer) => Request.deserialize(new Uint8Array(bytes))
      },
      respond: {
        path: "/Grpc.Queue/respond",
        requestStream: false,
        responseStream: false,
        requestSerialize: (message: Response) => Buffer.from(message.serialize()),
        requestDeserialize: (bytes: Buffer) => Response.deserialize(new Uint8Array(bytes)),
        responseSerialize: (message: Response.Result) => Buffer.from(message.serialize()),
        responseDeserialize: (bytes: Buffer) => Response.Result.deserialize(new Uint8Array(bytes))
      }
    };
    [method: string]: grpc_1.UntypedHandleCall;
    abstract pop(
      call: grpc_1.ServerUnaryCall<Request.Pop, Request>,
      callback: grpc_1.sendUnaryData<Request>
    ): void;
    abstract respond(
      call: grpc_1.ServerUnaryCall<Response, Response.Result>,
      callback: grpc_1.sendUnaryData<Response.Result>
    ): void;
  }
  export class QueueClient extends grpc_1.makeGenericClientConstructor(
    UnimplementedQueueService.definition,
    "Queue",
    {}
  ) {
    constructor(
      address: string,
      credentials: grpc_1.ChannelCredentials,
      options?: Partial<grpc_1.ChannelOptions>
    ) {
      super(address, credentials, options);
    }
    pop: GrpcUnaryServiceInterface<Request.Pop, Request> = (
      message: Request.Pop,
      metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Request>,
      options?: grpc_1.CallOptions | grpc_1.requestCallback<Request>,
      callback?: grpc_1.requestCallback<Request>
    ): grpc_1.ClientUnaryCall => {
      return super.pop(message, metadata, options, callback);
    };
    respond: GrpcUnaryServiceInterface<Response, Response.Result> = (
      message: Response,
      metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Response.Result>,
      options?: grpc_1.CallOptions | grpc_1.requestCallback<Response.Result>,
      callback?: grpc_1.requestCallback<Response.Result>
    ): grpc_1.ClientUnaryCall => {
      return super.respond(message, metadata, options, callback);
    };
  }
}
