#!/usr/bin/env bash

set -u -e -o pipefail


# We need to resolve the Bazel binary in the node modules because running Bazel
# through `yarn bazel` causes additional output that throws off the command stdout.
BAZEL_BIN=$(yarn bin)/bazel

# Build into a distinct output location so that artifacts from previous builds are not reused
BAZEL_OUTPUT_BASE=$(mktemp -d -t spica-release)
BAZEL="$BAZEL_BIN --output_base=$BAZEL_OUTPUT_BASE"
IMAGE_LABELS=`${BAZEL_BIN} query --output=label 'attr("tags", "\[.*release-with-spica.*\]", //stacks/... + //tools/...) intersect kind("container_push", //stacks/... + //tools/...)'`
echo $IMAGE_LABELS


# Build all targets concurrently
$BAZEL build --config=release $IMAGE_LABELS

for IMAGE_LABEL in $IMAGE_LABELS; do
    $BAZEL run --config=release $IMAGE_LABEL
done