var_1: &job_defaults
  working_directory: ~/spica
  docker:
    - image: circleci/node:11-browsers

var_2: &test_defaults
  <<: *job_defaults
  docker:
    - image: circleci/node:11-browsers
    - image: circleci/mongo:4.2

var_3: &setup_circleci_bazel_config
  run:
    name: Setting up CircleCI bazel configuration
    command: sudo cp .circleci/bazel.rc /etc/bazel.bazelrc

var_4: &cache_key infra-{{ checksum "yarn.lock" }}-{{ checksum "WORKSPACE" }}

var_5: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      # fallback to using the latest cache if no exact match is found
      - infra

var_6: &attach_workspace
  attach_workspace:
    at: ~/

var_7: &checkout_code
  checkout:
    # After checkout, rebase on top of master. By default, PRs are not rebased on top of master,
    # which we want. See https://discuss.circleci.com/t/1662
    post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
jobs:
  setup:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - run:
          name: "Installing dependencies"
          command: yarn install --frozen-lockfile --non-interactive
      - persist_to_workspace:
          root: ~/
          paths:
            - ./spica
            - ./bazel_repository_cache
  lint:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run: "yarn bazel:format -mode=check"
      - run: "yarn code:format-check"
  test:
    <<: *test_defaults
    steps:
      - *attach_workspace
      - *setup_circleci_bazel_config
      - run:
          name: "Running tests"
          command: (./node_modules/.bin/bazel query 'tests(//...)' --output label | xargs ./node_modules/.bin/bazel test) && yarn bazel shutdown
      - run:
          name: "Running tests"
          command: cd ./stacks/spica && yarn ng test --browsers=ChromeHeadless --watch=false --progress=false --reporters=spec
      - persist_to_workspace:
          root: ~/
          paths:
            - ./spica
            - ./bazel_repository_cache
      - save_cache:
          key: *cache_key
          paths:
            - "node_modules"
            - "docs/site/node_modules"
            - "stacks/spica/node_modules"
            - "~/bazel_repository_cache"
  deploy:
    <<: *job_defaults
    steps:
      - setup_remote_docker
      - *attach_workspace
      - *setup_circleci_bazel_config
      - gcp-gke/install
      - gcp-gke/init
      - run:
          name: "Configuring docker"
          command: |
            gcloud container clusters get-credentials $CLUSTER_NAME --zone $GOOGLE_COMPUTE_ZONE --project $GOOGLE_PROJECT_ID
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: "Deploying artifacts"
          command: ./node_modules/.bin/bazel run deploy.replace -- --force

workflows:
  version: 2
  default:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          # We should not depend on lint because we want to run them on parallel
          requires:
            - setup
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
