apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-application
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: api
      port: 4300
      targetPort: 4300
  selector:
    app: {{ .Release.Name }}-application