apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-database
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-database