apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-database
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-database
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  serviceName: {{ .Release.Name }}-database
  replicas: {{ .Values.database.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-database
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-database
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: helm
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:{{ .Values.database.version }}
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          resources:
{{ toYaml .Values.database.resources | indent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-data
      spec:
        storageClassName: {{.Values.database.storageClass}}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{.Values.database.storageSize}}
