apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-database
type: Opaque
stringData:
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }}
  replica-auth-key: {{ .Values.database.replicaAuthKey }}