apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-database
  labels:
    app.kubernetes.io/name: database-srv
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-database
    app.kubernetes.io/component: database