apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-database
spec:
  serviceName: {{ .Release.Name }}-database
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
    spec:
      initContainers:
        - name: replication-controller
          image: spicaengine/initcontainer:{{ $.Chart.AppVersion }}
          imagePullPolicy: Always
      containers:
        - name: mongo
          image: mongo:{{ .Values.database.version }}
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          resources:
{{ toYaml .Values.database.resources | indent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-data
      spec:
        storageClassName: {{.Values.database.storageClass}}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{.Values.database.storageSize}}
