apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-database-credentials
type: Opaque
stringData:
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ .Release.Name }}-database-replica-auth-key
type: Opaque
stringData:
  replica-auth-key: {{ .Values.database.replicaAuthKey }}