kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-version
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
data:
  VERSION: {{ .Chart.AppVersion }}