# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x44\x61tabase\"\xb6\x02\n\x06\x43hange\x12#\n\x04kind\x18\x01 \x01(\x0e\x32\x15.Database.Change.Kind\x12\x12\n\ncollection\x18\x02 \x01(\t\x12\x10\n\x08\x64ocument\x18\x03 \x01(\t\x12\x13\n\x0b\x64ocumentKey\x18\x04 \x01(\t\x12=\n\x11updateDescription\x18\x05 \x01(\x0b\x32\".Database.Change.UpdateDescription\x1a\x41\n\x11UpdateDescription\x12\x15\n\rupdatedFields\x18\x01 \x01(\t\x12\x15\n\rremovedFields\x18\x02 \x01(\t\x1a\x11\n\x03Pop\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x04Kind\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\x0b\n\x07REPLACE\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x32\x36\n\x05Queue\x12-\n\x03pop\x12\x14.Database.Change.Pop\x1a\x10.Database.Changeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGE']._serialized_start=29
  _globals['_CHANGE']._serialized_end=339
  _globals['_CHANGE_UPDATEDESCRIPTION']._serialized_start=198
  _globals['_CHANGE_UPDATEDESCRIPTION']._serialized_end=263
  _globals['_CHANGE_POP']._serialized_start=265
  _globals['_CHANGE_POP']._serialized_end=282
  _globals['_CHANGE_KIND']._serialized_start=284
  _globals['_CHANGE_KIND']._serialized_end=339
  _globals['_QUEUE']._serialized_start=341
  _globals['_QUEUE']._serialized_end=395
# @@protoc_insertion_point(module_scope)
