# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x05\x65vent\"r\n\x11SchedulingContext\x12)\n\x03\x65nv\x18\x02 \x03(\x0b\x32\x1c.event.SchedulingContext.Env\x12\x0f\n\x07timeout\x18\x03 \x01(\x02\x1a!\n\x03\x45nv\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"]\n\x06Target\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03\x63wd\x18\x02 \x01(\t\x12\x0f\n\x07handler\x18\x03 \x01(\t\x12)\n\x07\x63ontext\x18\x04 \x01(\x0b\x32\x18.event.SchedulingContext\"M\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.event.Type\x12\x1d\n\x06target\x18\x03 \x01(\x0b\x32\r.event.Target\"\x11\n\x03Pop\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x08\x43omplete\x12\n\n\x02id\x18\x01 \x01(\t\x1a\x08\n\x06Result*j\n\x04Type\x12\x08\n\x04HTTP\x10\x00\x12\x0c\n\x08\x44\x41TABASE\x10\x01\x12\x0c\n\x08SCHEDULE\x10\x03\x12\x0c\n\x08\x46IREHOSE\x10\x04\x12\n\n\x06SYSTEM\x10\x05\x12\n\n\x06\x42UCKET\x10\x06\x12\x0c\n\x08RABBITMQ\x10\x07\x12\x08\n\x04GRPC\x10\x08\x32]\n\x05Queue\x12\x1f\n\x03pop\x12\n.event.Pop\x1a\x0c.event.Event\x12\x33\n\x08\x63omplete\x12\x0f.event.Complete\x1a\x16.event.Complete.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TYPE']._serialized_start=365
  _globals['_TYPE']._serialized_end=471
  _globals['_SCHEDULINGCONTEXT']._serialized_start=22
  _globals['_SCHEDULINGCONTEXT']._serialized_end=136
  _globals['_SCHEDULINGCONTEXT_ENV']._serialized_start=103
  _globals['_SCHEDULINGCONTEXT_ENV']._serialized_end=136
  _globals['_TARGET']._serialized_start=138
  _globals['_TARGET']._serialized_end=231
  _globals['_EVENT']._serialized_start=233
  _globals['_EVENT']._serialized_end=310
  _globals['_POP']._serialized_start=312
  _globals['_POP']._serialized_end=329
  _globals['_COMPLETE']._serialized_start=331
  _globals['_COMPLETE']._serialized_end=363
  _globals['_COMPLETE_RESULT']._serialized_start=355
  _globals['_COMPLETE_RESULT']._serialized_end=363
  _globals['_QUEUE']._serialized_start=473
  _globals['_QUEUE']._serialized_end=566
# @@protoc_insertion_point(module_scope)
