# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'http.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhttp.proto\x12\x04Http\"$\n\x06Header\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"#\n\x05Param\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"k\n\tWriteHead\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x12\x15\n\rstatusMessage\x18\x03 \x01(\t\x12\x1d\n\x07headers\x18\x04 \x03(\x0b\x32\x0c.Http.Header\x1a\x08\n\x06Result\"=\n\x05Write\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x65ncoding\x18\x03 \x01(\t\x1a\x08\n\x06Result\"\xcb\x01\n\x07Request\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x15\n\rstatusMessage\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\r\n\x05query\x18\x06 \x01(\t\x12\x1d\n\x07headers\x18\x07 \x03(\x0b\x32\x0c.Http.Header\x12\x1b\n\x06params\x18\x08 \x03(\x0b\x32\x0b.Http.Param\x12\x0c\n\x04\x62ody\x18\t \x01(\x0c\x1a\x11\n\x03Pop\x12\n\n\x02id\x18\x01 \x01(\t\";\n\x03\x45nd\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x65ncoding\x18\x03 \x01(\t\x1a\x08\n\x06Result2\xb4\x01\n\x05Queue\x12\'\n\x03pop\x12\x11.Http.Request.Pop\x1a\r.Http.Request\x12\x34\n\twriteHead\x12\x0f.Http.WriteHead\x1a\x16.Http.WriteHead.Result\x12(\n\x05write\x12\x0b.Http.Write\x1a\x12.Http.Write.Result\x12\"\n\x03\x65nd\x12\t.Http.End\x1a\x10.Http.End.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'http_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEADER']._serialized_start=20
  _globals['_HEADER']._serialized_end=56
  _globals['_PARAM']._serialized_start=58
  _globals['_PARAM']._serialized_end=93
  _globals['_WRITEHEAD']._serialized_start=95
  _globals['_WRITEHEAD']._serialized_end=202
  _globals['_WRITEHEAD_RESULT']._serialized_start=194
  _globals['_WRITEHEAD_RESULT']._serialized_end=202
  _globals['_WRITE']._serialized_start=204
  _globals['_WRITE']._serialized_end=265
  _globals['_WRITE_RESULT']._serialized_start=194
  _globals['_WRITE_RESULT']._serialized_end=202
  _globals['_REQUEST']._serialized_start=268
  _globals['_REQUEST']._serialized_end=471
  _globals['_REQUEST_POP']._serialized_start=454
  _globals['_REQUEST_POP']._serialized_end=471
  _globals['_END']._serialized_start=473
  _globals['_END']._serialized_end=532
  _globals['_END_RESULT']._serialized_start=194
  _globals['_END_RESULT']._serialized_end=202
  _globals['_QUEUE']._serialized_start=535
  _globals['_QUEUE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
