export const BUCKET_DATA_LIMIT = Symbol.for("BUCKET_DATA_LIMIT");
export const BUCKET_DATA_HASH_SECRET = Symbol.for("BUCKET_DATA_HASH_SECRET");
export const BUCKET_DATA_ENCRYPTION_SECRET = Symbol.for("BUCKET_DATA_ENCRYPTION_SECRET");
