# Default values for spica.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
database:
    replicas: 2
    replicaSetName: "rs0"
    name: spica
    version: "4.2"
    storageSize: 2Gi
    storageClass: 
    resources: {}

application:
    secret: 
    defaultPassword: spica
    webBaseUrl: /spica/
    apiBaseUrl: /api/
    publicHost:
    storageSize: 2Gi
    storageClass: 
    apiResources: {}
    webResources: {}

ingress:
    host: 
    tls: []
    ingressClassName: nginx
    annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 15M
        nginx.ingress.kubernetes.io/client-body-buffer-size: 15Mb
        nginx.ingress.kubernetes.io/rewrite-target: /$1
