# Default values for spica.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
database:
  replicas: 1
  replicaSetName: 'rs0'
  name: spica
  version: '8.0.4'
  storageSize: 2Gi
  storageClass:
  resources: {}
  replicationControllerImage:
  spicaUsername:
  spicaPassword:
  rootUsername:
  rootPassword:
  replicaAuthKey:
  logLevel: 0
  profilingLevel: 1
  profilingSlowms: 100
  # probes
  # startup
  startupProbeInitialDelaySeconds: 15
  startupProbePeriodSeconds: 5
  startupProbeTimeoutSeconds: 5
  startupProbeFailureThreshold: 20
  # liveness
  livenessProbePeriodSeconds: 30
  livenessProbeTimeoutSeconds: 10
  livenessProbeFailureThreshold: 3
  # readiness
  readinessProbePeriodSeconds: 10
  readinessProbeTimeoutSeconds: 5
  readinessProbeFailureThreshold: 3

images:
  api: spicaengine/api
  web: spicaengine/spica
  replicationcontroller: spicaengine/mongoreplicationcontroller
  migrate: spicaengine/migrate

application:
  replicas: 1
  # Master key used to derive all module-specific secrets (hash, encryption, etc) except secrets specifically provided
  masterKey:
  # each secret will override the masterKey derived secret
  # optional if masterKey is provided, all required if not
  # passport secret for signing JWT tokens
  secret:
  # bucket data encryption/hash secret for encrypting/hashing data stored in buckets
  bucketDataHashSecret:
  bucketDataEncryptionSecret:
  # secret to encrypt secrets stored in secret module(especially function secrets)
  secretModuleEncryptionSecret:
  # user verification hash secret for hashing user verification tokens
  userVerificationHashSecret:
  # user provider encryption/hash secret for encrypting/hashing user email/phone number etc.
  userProviderEncryptionSecret:
  userProviderHashSecret:
  refreshTokenHashSecret:
  # sms provider configuration
  twilioAccountSid:
  twilioAuthToken:
  twilioFromNumber:
  defaultPassword: spica
  webBaseUrl: /spica/
  apiBaseUrl: /api/
  publicHost:
  storageSize: 2Gi
  storageClass:
  apiResources: {}
  webResources: {}
  args: []
  diskAccessMode: ReadWriteOnce
  serviceAccountName: default
  # probes
  # startup
  apiStartupProbeInitialDelaySeconds: 10
  apiStartupProbePeriodSeconds: 5
  apiStartupProbeTimeoutSeconds: 3
  apiStartupProbeFailureThreshold: 24
  # liveness
  apiLivenessProbePeriodSeconds: 15
  apiLivenessProbeTimeoutSeconds: 5
  apiLivenessProbeFailureThreshold: 3
  # readiness
  apiReadinessProbePeriodSeconds: 5
  apiReadinessProbeTimeoutSeconds: 5
  apiReadinessProbeFailureThreshold: 6
ingress:
  hosts: []
  tls: []
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 15M
    nginx.ingress.kubernetes.io/client-body-buffer-size: 15Mb
    nginx.ingress.kubernetes.io/rewrite-target: /$1
