name: Spica Continuous Integration Workflow

env:
  # use master later, can't use env here btw
  base_branch: nx-monorepo

on:
  pull_request:
    # use master later, can't use env here btw
    branches: ["nx-monorepo"]

jobs:
  setup:
    name: Setup NodeJS and Yarn packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout_branch
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: git fetch origin ${{ env.base_branch }}:${{ env.base_branch }}

      - name: Setup Node.js
        id: setup_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        id: install_deps
        run: yarn install --frozen-lockfile

      - name: Store node modules for next jobs
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: ./node_modules/

  lint:
    name: Check code format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Download node modules from setup
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: ./node_modules/

      - name: Check Format
        id: check_code
        run: yarn run format:check
