name: Spica Continuous Integration Workflow

env:
  # use master later
  base_branch: nx-monorepo
  VERSION: ${{ github.sha }}

on:
  pull_request:
    # use master later, can't use env here btw
    branches: ["nx-monorepo"]

jobs:
  lint_build_test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Free up some space on disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Restore Node Modules Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-node-modules-

      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx
          key: ${{ runner.os }}-nx-cache-${{ hashFiles('.nx') }}
          restore-keys: |
            ${{ runner.os }}-nx-cache-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch base branch
        run: git fetch origin ${{ env.base_branch }}:${{ env.base_branch }}

      - name: Disable Nx Cloud
        run: echo "NX_NO_CLOUD=true" >> $GITHUB_ENV

      - name: Check Format
        run: yarn run format:check

      # builds
      # docker images
      # - name: Build API
      #   run: yarn run build:api

      # - name: Build Mongo Replication Controller
      #   run: yarn run build:mongoreplicationcontroller

      # - name: Build Migrate
      #   run: yarn run build:migrate

      # # npm libraries
      # - name: Build CLI
      #   run: yarn run build:cli

      # - name: Build Devkit Packages
      #   run: yarn run build:devkit:*

      # tests
      # docker images
      - name: Test API
        run: yarn run test:api

      # - name: Test Migrate
      #   run: yarn run test:migrate

      # # npm libraries
      # - name: Test CLI
      #   run: yarn run test:cli

      # - name: Test Devkit Packages
      #   run: yarn run test:devkit:*
