name: Spica Continuous Integration Workflow

env:
  # use master later
  base_branch: nx-monorepo

on:
  pull_request:
    # use master later, can't use env here btw
    branches: ["nx-monorepo"]

jobs:
  lint_build_test:
    name: Lint, Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Restore Node Modules Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-node-modules-

      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx
          key: ${{ runner.os }}-nx-cache-${{ hashFiles('.nx') }}
          restore-keys: |
            ${{ runner.os }}-nx-cache-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch base branch
        run: git fetch origin ${{ env.base_branch }}:${{ env.base_branch }}

      - name: Check Format
        run: yarn run format:check

      - name: Disable Nx Cloud
        run: echo "NX_NO_CLOUD=true" >> $GITHUB_ENV

      # builds
      # docker images
      # - name: Build API
      #   run: yarn nx build-image api

      - name: Build Mongo Replication Controller
        run: yarn nx build-image mongoreplicationcontroller -t spicaengine/mongoreplicationcontroller:${{ github.sha }}

      # - name: Build Migrate
      #   run: yarn nx build-image migrate

      # npm libraries
      - name: Build CLI
        run: yarn nx build cli

      # - name: Build Devkit Packages
      #   run: |
      #     yarn nx run-many --target build --projects \
      #     api/function/packages/bucket \
      #     api/function/packages/database \
      #     api/function/packages/identity \
      #     api/function/packages/storage

      # # tests
      # # docker images
      - name: Test API
        run: yarn run test

      # - name: Test Migrate
      #   run: yarn nx test-image migrate

      # # npm libraries
      - name: Test CLI
        run: yarn nx test cli

      # - name: Test Devkit Packages
      #   run: |
      #     yarn nx run-many --target test --projects \
      #     api/function/packages/bucket \
      #     api/function/packages/database \
      #     api/function/packages/identity \
      #     api/function/packages/storage
