# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Spica Continuous Integration Workflow

on:
  pull_request:
    # use master later
    branches: ["nx-monorepo"]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        id: checkout_branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin nx-monorepo:nx-monorepo # Fetch the base branch explicitly

      - name: Setup Node.js ${{ matrix.node-version }}
        id: setup_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        id: install_deps
        run: yarn install --frozen-lockfile

      - name: Check Format
        id: check_code
        run: git fetch --all && yarn run format:check
