name: Spica CI/CD Workflow

env:
  # use master later
  base_branch: nx-monorepo
  VERSION: ${{ github.sha }}

on:
  pull_request:
    # use master later, can't use env here btw
    branches: ["nx-monorepo"]

jobs:
  container_test:
    name: Run Container Tests
    runs-on: ubuntu-latest
    uses: ./github/worksflow/setup.yml
    # needs: setup
    strategy:
      matrix:
        project:
          [
            api/activity/**,
            api/asset/**,
            api/bucket,
            api/bucket/cache/**,
            api/bucket/common/**,
            api/bucket/expression/**,
            api/bucket/graphql/**,
            api/bucket/history/**,
            api/bucket/hooks/**,
            api/bucket/realtime/**,
            api/bucket/services/**,
            api/dashboard/**,
            api/function,
            api/function/compiler/**,
            api/function/enqueuer/**,
            api/function/log/**,
            api/function/pkgmanager/**,
            api/function/queue/**,
            api/function/runtime/**,
            api/function/scheduler/**,
            api/function/webhook/**,
            api/passport/**,
            api/preference/**,
            api/replication/**,
            api/status/**,
            api/storage/**,
            api/versioncontrol/**,
            core/**,
            database/**,
            filter/**,
            cli/**,
            migrate/**
          ]

    steps:
      - name: Run Container Tests
        run: yarn run test-image:api --build-arg PROJECTS=${{matrix.project}}
