name: Spica Continuous Integration Workflow

env:
  # use master later, can't use env here btw
  base_branch: nx-monorepo

on:
  pull_request:
    # use master later, can't use env here btw
    branches: ["nx-monorepo"]

jobs:
  setup:
    name: Setup NodeJS and Yarn packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout_branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Cache all node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules  # Cache all node_modules across the entire repository
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }} # Cache key based on yarn.lock
          restore-keys: |
            ${{ runner.os }}-yarn-  # Fall back to key without hash of yarn.lock
            ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}  # Fall back to package.json if yarn.lock changes

      - name: Install dependencies
        id: install_deps
        run: yarn install --frozen-lockfile

  lint:
    name: Check code format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        id: checkout_branch
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: git fetch origin ${{ env.base_branch }}:${{ env.base_branch }}

      - name: Restore all node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules  # Restore all node_modules across the entire repository
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Check Format
        id: check_code
        run: yarn run format:check
