name: Spica Continuous Integration Workflow

env:
  # use master later, can't use env here btw
  base_branch: nx-monorepo

on:
  pull_request:
    # use master later, can't use env here btw
    branches: ["nx-monorepo"]

jobs:
  setup:
    name: Setup NodeJS and Yarn packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Fetch base branch
        run: git fetch origin ${{ env.base_branch }}:${{ env.base_branch }}

      - name: Check Format
        run: yarn run format:check

      # builds
      # docker images
      # - name: Build API
      #   run: yarn nx build-image api

      - name: Build Mongo Replication Controller
        run: yarn nx build-image mongoreplicationcontroller -t spicaengine/mongoreplicationcontroller:${{ github.sha }}

      # - name: Build Migrate
      #   run: yarn nx build-image migrate

      # npm libraries
      - name: Build CLI
        run: yarn nx build cli

      # - name: Build Devkit Packages
      #   run: |
      #     yarn nx run-many --target build --projects \
      #     api/function/packages/bucket \
      #     api/function/packages/database \
      #     api/function/packages/identity \
      #     api/function/packages/storage

      # # tests
      # # docker images
      # - name: Test API
      #   run: yarn nx test-image api

      # - name: Test Migrate
      #   run: yarn nx test-image migrate

      # # npm libraries
      - name: Test CLI
        run: yarn nx test cli

      # - name: Test Devkit Packages
      #   run: |
      #     yarn nx run-many --target test --projects \
      #     api/function/packages/bucket \
      #     api/function/packages/database \
      #     api/function/packages/identity \
      #     api/function/packages/storage
