name: Spica Continuous Integration Workflow

env:
  # use master later, can't use env here btw
  base_branch: nx-monorepo

on:
  pull_request:
    # use master later, can't use env here btw
    branches: ["nx-monorepo"]

jobs:
  setup:
    name: Setup NodeJS and Yarn packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout_branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup_nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        id: install_deps
        run: yarn install --frozen-lockfile

      - name: Save node modules
        id: node_modules_save
        uses: actions/cache@v3
        with:
          path: node_modules # Cache the node_modules folder
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }} # Use yarn.lock to define cache key
          restore-keys: |
            ${{ runner.os }}-yarn-  # Fall back if cache is not found
            ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}  # Fall back to package.json if yarn.lock changes

  lint:
    name: Check code format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        id: checkout_branch
        uses: actions/checkout@v4

      - name: Fetch base branch
        run: git fetch origin ${{ env.base_branch }}:${{ env.base_branch }}

      - name: Restore node_modules cache
        id: node_modules_restore
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Check Format
        id: check_code
        run: yarn run format:check
