name: Spica Master Deployment

env:
  VERSION: master
  BASE_URL: /spica/
  VITE_BASE_URL: https://master.spicaengine.com/api
on:
  push:
    branches: ["master"]

jobs:
  build_and_push:
    name: Build and Push (${{ matrix.project }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: api
            dir: apps/api
          - project: panel
            dir: apps/panel
          - project: migrate
            dir: apps/migrate
          - project: mongoreplicationcontroller
            dir: apps/mongoreplicationcontroller
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Restore Node Modules Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 600000

      - name: Restore Nx Cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-nx-

      - name: Prune project
        run: yarn nx prune ${{ matrix.project }}

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Restore Docker Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: docker-cache-mounts
          key: ${{ runner.os }}-docker-cache-${{ matrix.project }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-${{ matrix.project }}-

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dir }}/Dockerfile
          push: true
          tags: spicaengine/${{ matrix.project }}:${{ env.VERSION }}
          target: runner
          platforms: linux/amd64, linux/arm64
          cache-from: type=gha,scope=${{ matrix.project }}
          cache-to: type=gha,scope=${{ matrix.project }},mode=max

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: godfather
          location: us-central1-a
          project_id: spica-239113

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./deployment.yaml
          kubectl delete --all pods -n infrastructure-master-spicaengine-com
