name: Spica Github Releasing

# on:
#   push:
#     tags: ["*"]

env:
  tag_name: $(git describe --tags --abbrev=0)

on:
  pull_request:
    branches: ["master"]

jobs:
  create_github_release:
    name: Create Github Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: "true"
          files: "*"
          draft: true # until testing completed.
          tag_name: $tag_name
