name: Spica Github Releasing

# on:
#   push:
#     tags: ["*"]

env:
  last_tag: $(git describe --tags --abbrev=0)
  prev_tag: $(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))

on:
  pull_request:
    branches: ["master"]

jobs:
  create_github_release:
    name: Create Github Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release Notes
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
          -d '{"tag_name": ${{ env.last_tag }}, "previous_tag_name": ${{ env.prev_tag }}}'
