name: Spica Release

on:
  push:
    branches: ["optimize-release"]

jobs:
  docker-images:
    name: Release Docker image (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - api
          - migrate
          - mongoreplicationcontroller
        include:
          - target: api
            dockerfile: apps/api/Dockerfile
            image: spicaengine/api
          - target: migrate
            dockerfile: apps/migrate/Dockerfile
            image: spicaengine/migrate
          - target: mongoreplicationcontroller
            dockerfile: apps/mongoreplicationcontroller/Dockerfile
            image: spicaengine/mongoreplicationcontroller

    steps:
      - name: Free up some space on disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set the VERSION
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=0.18.11-pre1" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:${{ env.VERSION }}
          target: runner
          platforms: linux/amd64
          cache-from: type=gha,scope=${{ matrix.target }}
          cache-to: type=gha,scope=${{ matrix.target }},mode=max

  npm-packages:
    name: Release npm package (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - devkit:*
          - cli

    steps:
      - name: Free up some space on disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          cache-dependency-path: yarn.lock
          registry-url: https://registry.npmjs.org/

      - name: Restore Node Modules Cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 600000

      - name: Disable Nx Cloud
        run: echo "NX_NO_CLOUD=true" >> $GITHUB_ENV

      - name: Set the VERSION
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=0.18.11-pre1" >> $GITHUB_ENV

      - name: Set Yarn registry explicitly
        run: yarn config set registry https://registry.npmjs.org

      - name: Release npm packages
        run: yarn run publish:${{ matrix.target }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  helm-charts:
    name: Release Helm charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set the VERSION
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=0.18.11-pre1" >> $GITHUB_ENV

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Setup GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Login to GCP
        run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

      - name: Release Helm charts
        run: yarn run publish:charts
