name: Spica Version Release

env:
  base_branch: nx-monorepo

on:
  push:
    branches:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  hello:
    name: Test is it triggered.
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: ls
